Repository appKom/ravioli, pull requests merged in 2024-06, with the labels that each got.

#88 Updated readme
  README.md
Labels: documentation

#87 Removed all react imports
  .eslintrc.js
  src/App.tsx
  src/components/Badge.tsx
  src/components/DarkModeContainer.tsx
  src/components/Error.tsx
  src/components/EventCard.tsx
  src/components/EventCarousel.tsx
  src/components/Header.tsx
  src/components/Loading.tsx
  src/components/Logo/BekkLogo.tsx
  src/components/Logo/OnlineLogo.tsx
  src/components/SeasonalGraphic.jsx
  src/index.tsx
Labels: refactoring

#92 Added more cute messages
  src/lib/messages.ts
Labels: styling

#91 Made the seasonal graphic smaller
  src/components/Header.tsx
  src/components/SeasonalGraphic.tsx
Labels: styling

#95 Fix check darkmode every minute
  src/components/DarkModeContainer.tsx
Labels: bug
